### PR TITLE
Gaas create annotation project

### PR DESCRIPTION
**Pull request by nylander**
This is a new version of the script `gaas_create_annotation_project.pl` as per request from @LucileSol.

Now it basically creates a folder hierarchy, and does not require mandatory arguments (for copying `genome.fas` etc).

**NOTE**: The previous script had an option `-v` which was used for supplying the assembly version. **This is now changed!**

If one want to supply assembly version, the new option is `--assembly-version` (or `-a`).

The option `-v` (or `--version`) is now used for printing the version of the script itself.

This change in options can of course be undone.

### CODE REVIEW

**Comment by LucileSol** [comment]
seems all good to me! @aersoares81 want to try it? or add something?

**Comment by aersoares81** [comment]
Looks good, I'll give it a try soon-ish. I have a couple of suggestions of things we could add to it, we'll talk on Wednesday. :)

**Comment by aersoares81** [comment]
Some suggestions after out meeting today:

1) Add an additional directory "public_data" where we can store stuff for Maker's Protein Homology Evidence;
2) An option to symlink or copy RNAseq data from somewhere else into the project folder;
3) AnnotationPreprocessing.nf that we use to pre-process/clean the genome assemblies will output the "purified" version of the genome to a directory called to 'assembly/${fasta_file.baseName}_purified'. The original genome is inside /Genome. I think having these two directories is a bit redundant, so we either create 'assembly' instead of 'Genome', or change the output of AnnotationPreprocessing.nf to inside Genome instead.

**Review by aersoares81 — APPROVED** [review]
Thumbs up!

**Pull request merged**
