### PR TITLE
Changes for running webapollo with docker on other systems.

### PR DESCRIPTION
**Pull request by pontus**

### CODE REVIEW

**Review by viklund — APPROVED** [review]

**Comment by Juke34** [comment]
Can Lucile or someone else try the scripts to check they are working fine before to merge?
Or maybe it has already be done?

**Comment by Juke34** [comment]
At some point I'm wondering if we should not transplant webapollo related work/script/files into a dedicated repository.
What do you think?

**Comment by LucileSol** [comment]
I ran the scripts and they are working, we can create genomes, delete genomes, load tracks, delete tracks, load user tracks, delete user tracks, load bam. Anything I might have forgotten? 
We thought about first having all the script at the same location so for now in this repository but we can create a new repository if people thinks it is better.

**Comment by pontus** [comment]
(I don't have any opinions about keeping here or putting in another repo, if someone has, can they please clarify?)

**Pull request merged**
